sudo: false
language: node_js
node_js:
  - '0.12'
branches:
  only:
    - source
before_install:
  - rvm install 2.1.1
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'travis@yeoman.io'
  - gem install bundler
  - bundle install
# Silent the script output, we don't want any key made public in the Travis log
script: npm run-script deploy
env:
  global:
    secure: bAdIqjrnU4Vcsa1vF7svhbOq4FRkPUbmbELjMmOdU+nxdZNRQozc6ioVNa/mQZOlW33vgSiFfS9V+qJdWsEe4UjlTlwD5CHXnvc0+279wRhFSZ+MyM3M+YEE1/sMX7dRxHCamSwbz3OSYTatte4yTzt4VnW9eoBYq347aBvw5Fc=
