# Site settings
title: Openbizx Enterprise PHP Framework
email: agus.suhartono@gmail.com
description: 'Simple, Powerfull and Enterprise PHP Framework'  
baseurl: 'http://openbizx.github.io/'
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: openbizx
github_username:  openbizx

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
gems:
    - jekyll-redirect-from
latest_version: v0.35.0
current_node: 4.1.1
current_chrome: 45.0.2454.85
current_v8: 4.5.103.29
available_versions:
    
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Grunfile.js
    - package.json
    - script
    - spec